version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: melss
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    mem_limit: 512m  # Allocate sufficient memory for MySQL
    cpu_shares: 256

  backend:
    build:
      context: ./backend
    container_name: flask_container
    ports:
      - "5000:5000"
    depends_on:
      - db
    mem_limit: 256m
    cpu_shares: 128

  frontend:
    build:
      context: ./frontend
    container_name: react_container
    ports:
      - "3000:3000"  # Map port 3000
    depends_on:
      - backend
    mem_limit: 512m  # Allocate sufficient memory for React
    cpu_shares: 128

volumes:
  mysql_data:

networks:
  default:
    driver: bridge
