version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_container
    ports:
      - "3000:3000"  # Map port 3000
    environment:
      - REACT_APP_API_URL=http://backend:5000/todos

    mem_limit: 512m  # Allocate sufficient memory for React
    cpu_shares: 128

# networks:
#   default:
#     driver: bridge
